[build]
  command = "npm run build"
  publish = "www"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback para evitar erro 404 ao atualizar pÃ¡ginas internas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 